
__include__: [
  '../dataset/voc_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer_120e.yml',
  './include/rtdetr_r50vd.yml',
]


output_dir: ./output/v1_r18vd_120e_voc_SemanticAlign_highFF/

epoches: 120

PResNet:
  depth: 18
  freeze_at: -1
  freeze_norm: False
  pretrained: True


HybridEncoder:
  in_channels: [128, 256, 512]
  hidden_dim: 256
  expansion: 0.5


RTDETRTransformer:
  num_layers: 3



optimizer:
  type: AdamW
  params:
    - 
      params: '^(?=.*(?:norm|bn)).*$'
      weight_decay: 0.