
__include__: [
  '../dataset/voc_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer_120e.yml',
  './include/rtdetr_r50vd.yml',
]


output_dir: ./output/v1_r50vd_120e_voc_SpatialAlign_SpatialAlign/



epoches: 120